# Site settings
title: BCLUB.GOLF
email: hi@bclub.golf
description: >- 
  Join our exclusive BGOLF CLUB Discord and BGOLF CLUB TikTok to stay tapped in!
  Participate in our elite league, play at partner country club golf courses around the world, and enjoy exclusive discounts at our partner golf shops. Experience the excitement of golf with other passionate enthusiasts and make the most of your BGOLF Club membership!
baseurl: "" # e.g., /blog
url: "https://bclub.golf" # e.g., http://example.com
twitter_username: bitgolfclub
github_username: luvnft
permalink: /blog/:categories/:title/
sharing_image: /assets/images/bgolf-sharing-image.jpg

# Build settings
theme: minima
paginate: 6
paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing
exclude:
  - svelte-components
  - node_modules
  - package.json
  - package-lock.json
