# Site settings
title: BDISC.GOLF
email: play@bdisc.golf
description: >-
  BDISC.golf is the disc golf pro league played on our livestream platform and on TikTok with Duet challenges. Participate in our elite league, play at partner golf courses around the world, in parks, on university campuses, at local recreational areas, and urban pop-up goals. Use our disc search engine to access info on over 1k+ disc types. Earn Bitcoin BGOLF rewards for winning our social challenges.
baseurl: "https://bdisc.golf" # e.g., /blog
url: "https://bdisc.golf" # e.g., http://example.com
twitter_username: bitgolfclub
github_username: luvnft
permalink: /blog/:categories/:title/
sharing_image: /assets/images/bdisc-golf-sharing-image.jpg

# Build settings
theme: minima
paginate: 6
paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing
exclude:
  - svelte-components
  - node_modules
  - package.json
  - package-lock.json
