# Site settings
title: BDISC.GOLF
email: hi@bclub.golf
description: >- 
  Tap into our exclusive Frisbee Disc BDISC Discord and follow us on TikTok at @BDISCGOLF to stay tapped in.
  Participate in our elite league, play at partner golf courses around the world, in parks, on university campuses, at local recreational areas, and even at private disc golf courses. Win Bitcoin BGOLF rewards and enjoy exclusive discounts with our partner shops.
baseurl: "" # e.g., /blog
url: "https://bdisc.golf" # e.g., http://example.com
twitter_username: bitgolfclub
github_username: luvnft
permalink: /blog/:categories/:title/
sharing_image: /assets/images/bdisc-golf-sharing-image.jpg

# Build settings
theme: minima
paginate: 6
paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing
exclude:
  - svelte-components
  - node_modules
  - package.json
  - package-lock.json
